# Generated by Django 4.1.1 on 2022-09-23 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_book_books_bookcount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookcount',
            old_name='name',
            new_name='Book',
        ),
        migrations.CreateModel(
            name='IssueBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued', models.BooleanField()),
                ('Book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.books')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.student')),
            ],
        ),
    ]
