# Generated by Django 4.1.1 on 2022-09-30 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_books_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='publish_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
