# Generated by Django 4.1.1 on 2022-09-30 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_books_publish_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IssueBook',
            new_name='RequestedBook',
        ),
    ]
