# Generated by Django 4.1.1 on 2022-10-01 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_student_admission_no_alter_student_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(choices=[('CHE', 'Computer Hardware Engineering'), ('EC', 'Electronocs And Communications'), ('ME', 'Mechanical Engineering'), ('IE', 'Instrumentaion Engineering'), ('CE', 'Computer Engineering')], max_length=3, null=True),
        ),
    ]
