# Generated by Django 4.1.1 on 2022-10-05 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_student_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='admission_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='batch',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(blank=True, choices=[('', ''), ('CHE', 'Computer Hardware Engineering'), ('EC', 'Electronocs And Communications'), ('ME', 'Mechanical Engineering'), ('IE', 'Instrumentaion Engineering'), ('CE', 'Computer Engineering')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
