# Generated by Django 4.1.1 on 2022-10-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_books_image_alter_student_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestedbook',
            name='borrow_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='requestedbook',
            name='return_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
