# Generated by Django 4.1.1 on 2022-10-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_requestedbook_borrow_date_requestedbook_return_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestedbook',
            name='borrow_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requestedbook',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
