# Generated by Django 4.1.1 on 2022-10-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_requestedbook_borrow_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestedbook',
            name='borrow_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
