# Generated by Django 4.1.1 on 2022-10-08 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_student_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestedbook',
            name='return_request',
            field=models.BooleanField(default=False),
        ),
    ]
