# Generated by Django 4.1.1 on 2022-10-08 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_requestedbook_return_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.student'),
        ),
    ]
